### ISSUE TITLE
Crash in "Styles"

### ISSUE THREAD

**Issue by misery** [KDAB/GammaRay#142]
If we launch our app with gammaray and open "Styles" we want to switch from "Gtk+" to one of four "QStyleSheetStyle" entries but gammaray will crash with the following stacktrace.

Qt: 5.5.0
gammaray: 78278e5da8465c35baaeff53675841c519e90d7d (16. July 2015)

```
==3831==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x7fe2cb3a7ef6 bp 0x7ffdee00bee0 sp 0x7ffdee00bed0 T0)
    #0 0x7fe2cb3a7ef5 in QScopedPointer<QObjectData, QScopedPointerDeleter<QObjectData> >::operator->() const [..]/src/qt/qtbase/src/widgets/../../include/QtCore/../../src/corelib/tools/qscopedpointer.h:112
    #1 0x7fe2cb3a7ac7 in QObject::parent() const [..]/src/qt/qtbase/src/widgets/../../include/QtCore/../../src/corelib/kernel/qobject.h:419
    #2 0x7fe2cb3bb021 in QWidget::parentWidget() const [..]/src/qt/qtbase/src/widgets/../../include/QtWidgets/../../src/widgets/kernel/qwidget.h:846
    #3 0x7fe2cb48c378 in QStyleSheetStyle::drawPrimitive(QStyle::PrimitiveElement, QStyleOption const*, QPainter*, QWidget const*) const [..]/src/qt/qtbase/src/widgets/styles/qstylesheetstyle.cpp:4145
    #4 0x7fe2ae5a902c in GammaRay::PrimitiveModel::doData(int, int, int) const ([..]/build/lib/gammaray/2.4/qt5.5-x86_64/gammaray_styleinspector_plugin.so+0x1002c)
    #5 0x7fe2ae5a9d32 in GammaRay::AbstractStyleElementModel::data(QModelIndex const&, int) const ([..]/build/lib/gammaray/2.4/qt5.5-x86_64/gammaray_styleinspector_plugin.so+0x10d32)
    #6 0x7fe2c9c15340 in QAbstractItemModel::itemData(QModelIndex const&) const [..]/src/qt/qtbase/src/corelib/itemmodels/qabstractitemmodel.cpp:1730
    #7 0x7fe2c845c642 in GammaRay::RemoteModelServer::newRequest(GammaRay::Message const&) ([..]/build/lib/libgammaray_core-qt5.5-x86_64.so.2.4.0+0xb6642)
    #8 0x7fe2c9c82e7b in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const [..]/src/qt/qtbase/src/corelib/kernel/qmetaobject.cpp:2184
    #9 0x7fe2c9c82353 in QMetaObject::invokeMethod(QObject*, char const*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) [..]/src/qt/qtbase/src/corelib/kernel/qmetaobject.cpp:1479
    #10 0x7fe2c819b13d in GammaRay::Endpoint::dispatchMessage(GammaRay::Message const&) ([..]/build/lib/libgammaray_common-qt5.5-x86_64.so.2.4.0+0x2013d)
    #11 0x7fe2c8456bf0 in GammaRay::Server::messageReceived(GammaRay::Message const&) ([..]/build/lib/libgammaray_core-qt5.5-x86_64.so.2.4.0+0xb0bf0)
    #12 0x7fe2c8198940 in GammaRay::Endpoint::readyRead() ([..]/build/lib/libgammaray_common-qt5.5-x86_64.so.2.4.0+0x1d940)
    #13 0x7fe2c9cb5264 in QMetaObject::activate(QObject*, int, int, void**) [..]/src/qt/qtbase/src/corelib/kernel/qobject.cpp:3718
    #14 0x7fe2c9cb4a6f in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) [..]/src/qt/qtbase/src/corelib/kernel/qobject.cpp:3583
    #15 0x7fe2c9d4b66a in QIODevice::readyRead() [..]/src/qt/qtbase/src/corelib/.moc/moc_qiodevice.cpp:155
    #16 0x7fe2ca3a8e57 in QAbstractSocketPrivate::canReadNotification() [..]/src/qt/qtbase/src/network/socket/qabstractsocket.cpp:730
    #17 0x7fe2ca3af0ff in QAbstractSocketPrivate::readNotification() [..]/src/qt/qtbase/src/network/socket/qabstractsocket_p.h:69
    #18 0x7fe2ca39ab18 in QAbstractSocketEngine::readNotification() [..]/src/qt/qtbase/src/network/socket/qabstractsocketengine.cpp:152
    #19 0x7fe2ca3b7de3 in QReadNotifier::event(QEvent*) [..]/src/qt/qtbase/src/network/socket/qnativesocketengine.cpp:1169
    #20 0x7fe2cb3b7663 in QApplicationPrivate::notify_helper(QObject*, QEvent*) [..]/src/qt/qtbase/src/widgets/kernel/qapplication.cpp:3717
    #21 0x7fe2cb3b4dc2 in QApplication::notify(QObject*, QEvent*) [..]/src/qt/qtbase/src/widgets/kernel/qapplication.cpp:3161
    #22 0x7fe2c9c768c7 in QCoreApplication::notifyInternal(QObject*, QEvent*) [..]/src/qt/qtbase/src/corelib/kernel/qcoreapplication.cpp:965
    #23 0x7fe2c9c7a5d4 in QCoreApplication::sendEvent(QObject*, QEvent*) [..]/src/qt/qtbase/src/corelib/../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:224
    #24 0x7fe2c9cebd1b in socketNotifierSourceDispatch(_GSource*, int (*)(void*), void*) [..]/src/qt/qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:101
    #25 0x7fe2c79cd9fc in g_main_context_dispatch (/usr/lib/libglib-2.0.so.0+0x499fc)
    #26 0x7fe2c79cdcdf  (/usr/lib/libglib-2.0.so.0+0x49cdf)
    #27 0x7fe2c79cdd8b in g_main_context_iteration (/usr/lib/libglib-2.0.so.0+0x49d8b)
    #28 0x7fe2c9cec9ed in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) [..]/src/qt/qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:420
    #29 0x7fe2bfc9fc1f in QPAEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) [..]/src/qt/qtbase/src/platformsupport/eventdispatchers/qeventdispatcher_glib.cpp:115
    #30 0x7fe2c9c73485 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) [..]/src/qt/qtbase/src/corelib/kernel/qeventloop.cpp:128
    #31 0x7fe2c9c73779 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) [..]/src/qt/qtbase/src/corelib/kernel/qeventloop.cpp:204
    #32 0x7fe2c9c76fa5 in QCoreApplication::exec() [..]/src/qt/qtbase/src/corelib/kernel/qcoreapplication.cpp:1229
    #33 0x7fe2caca8ea7 in QGuiApplication::exec() [..]/src/qt/qtbase/src/gui/kernel/qguiapplication.cpp:1528
    #34 0x7fe2cb3b479c in QApplication::exec() [..]/src/qt/qtbase/src/widgets/kernel/qapplication.cpp:2977
    #35 0x4e488d in main [..]/src/main.cpp:140:57
    #36 0x7fe2c873a78f in __libc_start_main (/usr/lib/libc.so.6+0x2078f)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV [..]/src/qt/qtbase/src/widgets/../../include/QtCore/../../src/corelib/tools/qscopedpointer.h:112 QScopedPointer<QObjectData, QScopedPointerDeleter<QObjectData> >::operator->() const

```

**Comment by vkrause** [comment]
Patch submitted to Qt: https://codereview.qt-project.org/#/c/121769/
