### ISSUE TITLE
quickinspectortest fails

### ISSUE THREAD

**Issue by krf** [KDAB/GammaRay#298]
Regression introduced by #284.

ASAN trace:
```
36: Test command: /home/build/Buildbot/gammaray-qt57-linux64/build/bin/quickinspectortest
36: Test timeout computed to be: 9.99988e+06
36: ********* Start testing of QuickInspectorTest *********
36: Config: Using QtTest library 5.7.0, Qt 5.7.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 4.9.1 20140922 (Red Hat 4.9.1-10))
36: PASS   : QuickInspectorTest::initTestCase()
36: QWARN  : QuickInspectorTest::testModelsReparent() Failed to connect to launcher, can't receive probe settings! "QLocalSocket::connectToServer: Invalid name"
36: QWARN  : QuickInspectorTest::testModelsReparent() QMetaProperty::read: Unable to handle unregistered datatype 'QQuickAnchors*' for property 'QQuickItem::anchors'
36: QWARN  : QuickInspectorTest::testModelsReparent() QObject::disconnect: Unexpected null parameter
36: ASAN:SIGSEGV
36: =================================================================
36: ==26942==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x7f5c44005e60 bp 0x7ffd514b47b0 sp 0x7ffd514b45e8 T0)
36:     #0 0x7f5c44005e5f  (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Quick.so.5+0x19de5f)
36:     #1 0x7f5c277e6c56 in GammaRay::QuickOverlay::placeOn(GammaRay::ItemOrLayoutFacade) /home/build/Buildbot/gammaray-qt57-linux64/source/plugins/quickinspector/quickoverlay.cpp:135
36:     #2 0x7f5c27790bda in GammaRay::QuickInspector::itemSelectionChanged(QItemSelection const&) /home/build/Buildbot/gammaray-qt57-linux64/source/plugins/quickinspector/quickinspector.cpp:534
36:     #3 0x7f5c2779b70f in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<QItemSelection const&>, void, void (GammaRay::QuickInspector::*)(QItemSelection const&)>::call(void (GammaRay::QuickInspector::*)(QItemSelection const&), GammaRay::QuickInspector*, void**) /home/build/Qt5/5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h:507
36:     #4 0x7f5c2779b70f in void QtPrivate::FunctionPointer<void (GammaRay::QuickInspector::*)(QItemSelection const&)>::call<QtPrivate::List<QItemSelection const&>, void>(void (GammaRay::QuickInspector::*)(QItemSelection const&), GammaRay::QuickInspector*, void**) /home/build/Qt5/5.7.0/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h:526
36:     #5 0x7f5c2779b70f in QtPrivate::QSlotObject<void (GammaRay::QuickInspector::*)(QItemSelection const&), QtPrivate::List<QItemSelection const&>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) /home/build/Qt5/5.7.0/5.7/gcc_64/include/QtCore/qobject_impl.h:149
36:     #6 0x7f5c42fdc77c in QMetaObject::activate(QObject*, int, int, void**) (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Core.so.5+0x29977c)
36:     #7 0x7f5c42f69c16 in QItemSelectionModel::selectionChanged(QItemSelection const&, QItemSelection const&) (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Core.so.5+0x226c16)
36:     #8 0x7f5c42f6ff27  (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Core.so.5+0x22cf27)
36:     #9 0x7f5c42f73868  (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Core.so.5+0x230868)
36:     #10 0x7f5c42fdc055 in QMetaObject::activate(QObject*, int, int, void**) (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Core.so.5+0x299055)
36:     #11 0x7f5c4304edd3 in QAbstractItemModel::rowsAboutToBeRemoved(QModelIndex const&, int, int, QAbstractItemModel::QPrivateSignal) (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Core.so.5+0x30bdd3)
36:     #12 0x7f5c42f62232 in QAbstractItemModel::beginRemoveRows(QModelIndex const&, int, int) (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Core.so.5+0x21f232)
36:     #13 0x7f5c42f8476c  (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Core.so.5+0x24176c)
36:     #14 0x7f5c42f84904  (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Core.so.5+0x241904)
36:     #15 0x7f5c42f8afa7  (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Core.so.5+0x247fa7)
36:     #16 0x7f5c42fbf259 in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Core.so.5+0x27c259)
36:     #17 0x7f5c41aad77a in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const /home/build/Qt5/5.7.0/5.7/gcc_64/include/QtCore/qmetaobject.h:123
36:     #18 0x7f5c41aad77a in KRecursiveFilterProxyModelPrivate::invokeRowsAboutToBeRemoved(QModelIndex const&, int, int) /home/build/Buildbot/gammaray-qt57-linux64/source/3rdparty/kde/krecursivefilterproxymodel.cpp:131
36:     #19 0x7f5c41aad77a in KRecursiveFilterProxyModelPrivate::sourceRowsAboutToBeRemoved(QModelIndex const&, int, int) /home/build/Buildbot/gammaray-qt57-linux64/source/3rdparty/kde/krecursivefilterproxymodel.cpp:256
36:     #20 0x7f5c41aaf139 in KRecursiveFilterProxyModel::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) /home/build/Buildbot/gammaray-qt57-linux64/build/3rdparty/kde/moc_krecursivefilterproxymodel.cpp:99
36:     #21 0x7f5c42fdc055 in QMetaObject::activate(QObject*, int, int, void**) (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Core.so.5+0x299055)
36:     #22 0x7f5c4304edd3 in QAbstractItemModel::rowsAboutToBeRemoved(QModelIndex const&, int, int, QAbstractItemModel::QPrivateSignal) (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Core.so.5+0x30bdd3)
36:     #23 0x7f5c42f62232 in QAbstractItemModel::beginRemoveRows(QModelIndex const&, int, int) (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Core.so.5+0x21f232)
36:     #24 0x7f5c277bb5c6 in GammaRay::QuickItemModel::removeItem(QQuickItem*, bool) /home/build/Buildbot/gammaray-qt57-linux64/source/plugins/quickinspector/quickitemmodel.cpp:254
36:     #25 0x7f5c277bbfdc in GammaRay::QuickItemModel::itemWindowChanged() /home/build/Buildbot/gammaray-qt57-linux64/source/plugins/quickinspector/quickitemmodel.cpp:312
36:     #26 0x7f5c277e1164 in GammaRay::QuickItemModel::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) /home/build/Buildbot/gammaray-qt57-linux64/build/plugins/quickinspector/moc_quickitemmodel.cpp:87
36:     #27 0x7f5c42fdc055 in QMetaObject::activate(QObject*, int, int, void**) (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Core.so.5+0x299055)
36:     #28 0x7f5c43fef241 in QQuickItem::windowChanged(QQuickWindow*) (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Quick.so.5+0x187241)
36:     #29 0x7f5c43ffcd1e in QQuickItemPrivate::derefWindow() (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Quick.so.5+0x194d1e)
36:     #30 0x7f5c43ffef8d in QQuickItem::~QQuickItem() (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Quick.so.5+0x196f8d)
36:     #31 0x7f5c4414218d  (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Quick.so.5+0x2da18d)
36:     #32 0x7f5c4400adac in QQuickWindow::~QQuickWindow() (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Quick.so.5+0x1a2dac)
36:     #33 0x7f5c440b67e8 in QQuickView::~QQuickView() (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Quick.so.5+0x24e7e8)
36:     #34 0x408690 in QuickInspectorTest::cleanup() /home/build/Buildbot/gammaray-qt57-linux64/source/tests/quickinspectortest.cpp:139
36:     #35 0x408690 in QuickInspectorTest::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) /home/build/Buildbot/gammaray-qt57-linux64/build/tests/quickinspectortest.moc:99
36:     #36 0x40955e in QuickInspectorTest::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) /home/build/Buildbot/gammaray-qt57-linux64/build/tests/quickinspectortest.moc:92
36:     #37 0x7f5c42fbf259 in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Core.so.5+0x27c259)
36:     #38 0x7f5c4446bd20  (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Test.so.5+0x13d20)
36:     #39 0x7f5c4446c5ad  (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Test.so.5+0x145ad)
36:     #40 0x7f5c4446cba1  (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Test.so.5+0x14ba1)
36:     #41 0x7f5c4446d0ae in QTest::qExec(QObject*, int, char**) (/home/build/Qt5/5.7.0/5.7/gcc_64/lib/libQt5Test.so.5+0x150ae)
36:     #42 0x40739a in main /home/build/Buildbot/gammaray-qt57-linux64/source/tests/quickinspectortest.cpp:322
36:     #43 0x7f5c4240282f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
36:     #44 0x407648 in _start (/home/build/Buildbot/gammaray-qt57-linux64/build/bin/quickinspectortest+0x407648)
36: 
36: AddressSanitizer can not provide additional info.
36: SUMMARY: AddressSanitizer: SEGV ??:0 ??
36: ==26942==ABORTING
36/37 Test #36: quickinspectortest ...............***Failed    1.76 sec
```

Looks like `QQuickItem::window()` may return a nullptr.

**Comment by krf** [comment]
Fixed by:

```
commit 7cebc1a2f3d9d1058e97931d92512e0d269015a5
Author: Volker Krause <volker.krause@kdab.com>
Date:   Mon Jan 9 15:22:16 2017 +0100

    Fix crash when encountering items already removed from a scene
```
