### ISSUE TITLE
Crashes in QFileDialogPrivate::retranslateStrings when translations involved and using native file dialogs

### ISSUE THREAD

**Issue by krf** [KDAB/GammaRay#321]
This is merely for tracking this -- it already got solved.

Reported by user on our IRC channel:
```
<estan> hi folks. i just tried installing 2.7.0 on Kubuntu 16.04, from the repo at OBS. when i try to launch my executable (with access mode "Out-of-process, local-only"), i just get "Injector error: Process crashed" in the terminal.
<estan> this is with Qt 5.5.1, my application is built in Debug mode (using CMake).
<estan> launching e.g. /usr/bin/kate works fine.
<estan> (and my application doesn't crash when i plain run it ...)
```

The backtrace when running gammaray under GDB (`GAMMARAY_GDB=1 gammaray ...`):
```
Thread 1 "orexplore-insig" received signal SIGSEGV, Segmentation fault.
QFileDialogPrivate::retranslateStrings (this=this@entry=0x752080) at dialogs/qfiledialog.cpp:671
671     dialogs/qfiledialog.cpp: Filen eller katalogen finns inte.
(gdb)
(gdb) bt
#0  QFileDialogPrivate::retranslateStrings (this=this@entry=0x752080) at dialogs/qfiledialog.cpp:671
#1  0x00007ffff7167009 in QFileDialog::changeEvent (this=0x6eb890, e=0xaa7840) at dialogs/qfiledialog.cpp:519
#2  0x00007ffff6f9ffcc in QWidget::event (this=0x6eb890, event=0xaa7840) at kernel/qwidget.cpp:8960
#3  0x00007ffff6f5d05c in QApplicationPrivate::notify_helper (this=this@entry=0x66a3a0, receiver=receiver@entry=0x6eb890,
    e=e@entry=0xaa7840) at kernel/qapplication.cpp:3716
#4  0x00007ffff6f62516 in QApplication::notify (this=0x7fffffffcbd0, receiver=0x6eb890, e=0xaa7840)
    at kernel/qapplication.cpp:3499
#5  0x00007ffff666a38b in QCoreApplication::notifyInternal (this=0x7fffffffcbd0, receiver=0x6eb890, event=event@entry=0xaa7840)
    at kernel/qcoreapplication.cpp:965
#6  0x00007ffff6fa0018 in QCoreApplication::sendEvent (event=0xaa7840, receiver=<optimized out>)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:224
#7  QWidget::event (this=this@entry=0x7fffffffcbe0, event=event@entry=0xaa7840) at kernel/qwidget.cpp:8966
#8  0x00007ffff70b5d7b in QMainWindow::event (this=0x7fffffffcbe0, event=0xaa7840) at widgets/qmainwindow.cpp:1495
#9  0x00007ffff6f5d05c in QApplicationPrivate::notify_helper (this=this@entry=0x66a3a0, receiver=receiver@entry=0x7fffffffcbe0,
    e=e@entry=0xaa7840) at kernel/qapplication.cpp:3716
#10 0x00007ffff6f62516 in QApplication::notify (this=0x7fffffffcbd0, receiver=0x7fffffffcbe0, e=0xaa7840)
    at kernel/qapplication.cpp:3499
#11 0x00007ffff666a38b in QCoreApplication::notifyInternal (this=0x7fffffffcbd0, receiver=0x7fffffffcbe0,
    event=event@entry=0xaa7840) at kernel/qcoreapplication.cpp:965
#12 0x00007ffff666c786 in QCoreApplication::sendEvent (event=0xaa7840, receiver=<optimized out>)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:224
#13 QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x66a510)
    at kernel/qcoreapplication.cpp:1593
#14 0x00007ffff666cc68 in QCoreApplication::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0)
    at kernel/qcoreapplication.cpp:1451
#15 0x00007ffff66c03c3 in postEventSourceDispatch (s=0x6c1890) at kernel/qeventdispatcher_glib.cpp:271
#16 0x00007fffef9f4197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007fffef9f43f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007fffef9f449c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff66c07cf in QEventDispatcherGlib::processEvents (this=0x6bd4d0, flags=...) at kernel/qeventdispatcher_glib.cpp:418
#20 0x00007ffff6667b4a in QEventLoop::exec (this=0x7fffffffc610, flags=...) at kernel/qeventloop.cpp:204
#21 0x00007fffd9f0577e in KJob::exec() () from /usr/lib/x86_64-linux-gnu/libKF5CoreAddons.so.5
#22 0x00007fffe024089d in KFileWidget::KFileWidget(QUrl const&, QWidget*) ()
   from /usr/lib/x86_64-linux-gnu/libKF5KIOFileWidgets.so.5
#23 0x00007fffe04c29ab in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/KDEPlatformTheme.so
#24 0x00007fffe04c2ef2 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/KDEPlatformTheme.so
#25 0x00007fffe04b82da in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/KDEPlatformTheme.so
#26 0x00007ffff7156a05 in QDialogPrivate::platformHelper (this=this@entry=0x752080) at dialogs/qdialog.cpp:94
#27 0x00007ffff716a1b8 in QFileDialogPrivate::platformFileDialogHelper (this=0x752080) at dialogs/qfiledialog_p.h:112
#28 QFileDialogPrivate::init (this=this@entry=0x752080, directory=..., nameFilter=..., caption=...)
    at dialogs/qfiledialog.cpp:2771
#29 0x00007ffff716a43a in QFileDialog::QFileDialog (this=0x6eb890, parent=0x7fffffffcbe0, caption=..., directory=..., filter=...)
    at dialogs/qfiledialog.cpp:369
#30 0x00007ffff79705fc in MainWindow::MainWindow(QWidget*) ()
   from /home/estan/insight-inst/lib/orexplore-insight/libinsightview.so
#31 0x0000000000402b31 in main ()
(gdb)
```

**Comment by krf** [comment]
This is an upstream bug in Qt, fixed by:
https://codereview.qt-project.org/#/c/185750/
