### ISSUE TITLE
master branch and 2.11.0 are crashing all the time here

### ISSUE THREAD

**Issue by patrickelectric** [KDAB/GammaRay#563]
```
Application: gammaray-client (gammaray-client), signal: Aborted
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Current thread is 1 (Thread 0x7eff935005c0 (LWP 29806))]

Thread 2 (Thread 0x7eff88ac3700 (LWP 29808)):
#0  0x00007eff96c64667 in poll () at /usr/lib/libc.so.6
#1  0x00007eff95ae8a80 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007eff95ae8b51 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007eff9734d9bc in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#4  0x00007eff972f45ec in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#5  0x00007eff971272f5 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007eff92faab37 in  () at /usr/lib/libQt5DBus.so.5
#7  0x00007eff97128520 in  () at /usr/lib/libQt5Core.so.5
#8  0x00007eff9663157f in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007eff96c6f0e3 in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7eff935005c0 (LWP 29806)):
[KCrash Handler]
#6  0x00007eff96bad755 in raise () at /usr/lib/libc.so.6
#7  0x00007eff96b98851 in abort () at /usr/lib/libc.so.6
#8  0x00007eff970ed8b6 in  () at /usr/lib/libQt5Core.so.5
#9  0x00007eff970ecce2 in qt_assert_x(char const*, char const*, char const*, int) () at /usr/lib/libQt5Core.so.5
#10 0x00007eff982edad4 in GammaRay::RemoteModel::newMessage(GammaRay::Message const&) (this=0x55864f8feeb0, msg=...) at /home/patrick/git/kdab/gammaray/client/remotemodel.cpp:495
#11 0x00007eff982e3162 in GammaRay::RemoteModel::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x55864f8feeb0, _c=QMetaObject::InvokeMetaMethod, _id=4, _a=0x7ffda5ebe190) at /home/patrick/git/kdab/gammaray/b/client/gammaray_client_autogen/EWIEGA46WW/moc_remotemodel.cpp:133
#12 0x00007eff97303efd in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const () at /usr/lib/libQt5Core.so.5
#13 0x00007eff98281ac6 in QMetaMethod::invoke(QObject*, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const (this=0x55864f7be580, object=0x55864f8feeb0, val0=..., val1=..., val2=..., val3=..., val4=..., val5=..., val6=..., val7=..., val8=..., val9=...) at /usr/include/qt/QtCore/qmetaobject.h:137
#14 0x00007eff98280d49 in GammaRay::Endpoint::dispatchMessage(GammaRay::Message const&) (this=0x55864f5ee680, msg=...) at /home/patrick/git/kdab/gammaray/common/endpoint.cpp:360
#15 0x00007eff982e8233 in GammaRay::Client::messageReceived(GammaRay::Message const&) (this=0x55864f5ee680, msg=...) at /home/patrick/git/kdab/gammaray/client/client.cpp:226
#16 0x00007eff9827f8b3 in GammaRay::Endpoint::readyRead() (this=0x55864f5ee680) at /home/patrick/git/kdab/gammaray/common/endpoint.cpp:169
#17 0x00007eff9828794b in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (GammaRay::Endpoint::*)()>::call(void (GammaRay::Endpoint::*)(), GammaRay::Endpoint*, void**) (f=(void (GammaRay::Endpoint::*)(GammaRay::Endpoint * const)) 0x7eff9827f814 <GammaRay::Endpoint::readyRead()>, o=0x55864f5ee680, arg=0x7ffda5ebe730) at /usr/include/qt/QtCore/qobjectdefs_impl.h:152
#18 0x00007eff98286eef in QtPrivate::FunctionPointer<void (GammaRay::Endpoint::*)()>::call<QtPrivate::List<>, void>(void (GammaRay::Endpoint::*)(), GammaRay::Endpoint*, void**) (f=(void (GammaRay::Endpoint::*)(GammaRay::Endpoint * const)) 0x7eff9827f814 <GammaRay::Endpoint::readyRead()>, o=0x55864f5ee680, arg=0x7ffda5ebe730) at /usr/include/qt/QtCore/qobjectdefs_impl.h:185
#19 0x00007eff98285dd2 in QtPrivate::QSlotObject<void (GammaRay::Endpoint::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x55864f12c010, r=0x55864f5ee680, a=0x7ffda5ebe730, ret=0x0) at /usr/include/qt/QtCore/qobjectdefs_impl.h:414
#20 0x00007eff97321b70 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#21 0x00007eff9673ad75 in  () at /usr/lib/libQt5Network.so.5
#22 0x00007eff9673ae0b in  () at /usr/lib/libQt5Network.so.5
#23 0x00007eff9674d532 in  () at /usr/lib/libQt5Network.so.5
#24 0x00007eff97cab4d5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#25 0x00007eff97cb4a21 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#26 0x00007eff972f59c2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#27 0x00007eff9734e5f6 in  () at /usr/lib/libQt5Core.so.5
#28 0x00007eff95ae6cf4 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#29 0x00007eff95ae8b11 in  () at /usr/lib/libglib-2.0.so.0
#30 0x00007eff95ae8b51 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#31 0x00007eff9734d9a3 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#32 0x00007eff972f45ec in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#33 0x00007eff972fc326 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#34 0x000055864eb63911 in main(int, char**) (argc=2, argv=0x7ffda5ebeeb8) at /home/patrick/git/kdab/gammaray/client/main.cpp:79
[Inferior 1 (process 29806) detached]

```

**Comment by Waqar144** [comment]
A new gammaray version has been released, please try with latest.
