### ISSUE TITLE
Crash when accessing Qt Quick Scene

### ISSUE THREAD

**Issue by mitchcurtis** [KDAB/GammaRay#586]
<img width="532" alt="Screen Shot 2019-12-07 at 2 32 01 pm" src="https://user-images.githubusercontent.com/6002340/70375479-7dd39700-18fe-11ea-8879-b0ccc0145f50.png">

```
Process:               tshnm-iso [99820]
Path:                  /Users/USER/*/tshnm-iso.app/Contents/MacOS/tshnm-iso
Identifier:            org.example.tshnm-iso
Version:               1.0 (1.0.0)
Code Type:             X86-64 (Native)
Parent Process:        Qt Creator [79114]
Responsible:           tshnm-iso [99820]
User ID:               501

Date/Time:             2019-12-07 14:31:08.519 +0100
OS Version:            Mac OS X 10.14.6 (18G1012)
Report Version:        12
Bridge OS Version:     3.0 (14Y906)

Time Awake Since Boot: 520000 seconds
Time Since Wake:       3200 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

External Modification Warnings:
Debugger attached to process.

VM Regions Near 0:
--> 
    __TEXT                 0000000102ff3000-0000000103c0a000 [ 12.1M] r-x/rwx SM=COW  /Users/USER/*/tshnm-iso.app/Contents/MacOS/tshnm-iso

Application Specific Information:
=================================================================
==99820==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000107b28049 bp 0x7ffeecc08710 sp 0x7ffeecc084e0 T0)
==99820==The signal is caused by a READ memory access.
==99820==Hint: address points to the zero page.
    #0 0x107b28048 in QQuickWindowPrivate::renderSceneGraph(QSize const&, QSize const&) (QtQuick:x86_64+0x49e048)
    #1 0x1079911d4 in QSGGuiThreadRenderLoop::renderWindow(QQuickWindow*) (QtQuick:x86_64+0x3071d4)
    #2 0x107b3ee24 in QQuickWindow::event(QEvent*) (QtQuick:x86_64+0x4b4e24)
    #3 0x108aa964a in QApplicationPrivate::notify_helper(QObject*, QEvent*) (QtWidgets:x86_64+0x3164a)
    #4 0x108aade89 in QApplication::notify(QObject*, QEvent*) (QtWidgets:x86_64+0x35e89)
    #5 0x1043752cc in QCoreApplication::notifyInternal2(QObject*, QEvent*) (QtCore:x86_64+0x6b02cc)
    #6 0x104e57b59 in QPlatformWindow::deliverUpdateRequest() (QtGui:x86_64+0x75b59)
    #7 0x1102d003d in QCocoaWindow::deliverUpdateRequest() (libqcocoa.dylib:x86_64+0x5203d)
    #8 0x110296db1 in QCocoaScreen::deliverUpdateRequests() (libqcocoa.dylib:x86_64+0x18db1)
    #9 0x109e285a5 in __wrap_dispatch_source_set_event_handler_block_invoke (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x565a5)
    #10 0x7fff7326d63c in _dispatch_client_callout (libdispatch.dylib:x86_64+0x363c)
    #11 0x7fff7326fde5 in _dispatch_continuation_pop (libdispatch.dylib:x86_64+0x5de5)
    #12 0x7fff7327ef41 in _dispatch_source_invoke (libdispatch.dylib:x86_64+0x14f41)
    #13 0x7fff7327854a in _dispatch_main_queue_callback_4CF (libdispatch.dylib:x86_64+0xe54a)
    #14 0x7fff47354a86 in __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ (CoreFoundation:x86_64h+0x3ba86)
    #15 0x7fff473541b0 in __CFRunLoopRun (CoreFoundation:x86_64h+0x3b1b0)
    #16 0x7fff4735366d in CFRunLoopRunSpecific (CoreFoundation:x86_64h+0x3a66d)
    #17 0x7fff465b21aa in RunCurrentEventLoopInMode (HIToolbox:x86_64+0xb1aa)
    #18 0x7fff465b1ee4 in ReceiveNextEventCommon (HIToolbox:x86_64+0xaee4)
    #19 0x7fff465b1c75 in _BlockUntilNextEventMatchingListInModeWithFilter (HIToolbox:x86_64+0xac75)
    #20 0x7fff4494a77c in _DPSNextEvent (AppKit:x86_64+0x1a77c)
    #21 0x7fff4494946a in -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] (AppKit:x86_64+0x1946a)
    #22 0x7fff44943587 in -[NSApplication run] (AppKit:x86_64+0x13587)
    #23 0x110316a04 in QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (libqcocoa.dylib:x86_64+0x98a04)
    #24 0x104367296 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (QtCore:x86_64+0x6a2296)
    #25 0x1043771e2 in QCoreApplication::exec() (QtCore:x86_64+0x6b21e2)
    #26 0x10300e0e1 in TshnmApplication::doRun(int&, char**) TshnmApplication.cpp:380
    #27 0x1084fcf87 in AbstractApplication::run(int&, char**) AbstractApplication.cpp:48
    #28 0x103037406 in main main.cpp:17
    #29 0x102ff4753 in start (tshnm-iso:x86_64+0x100001753)
 
==99820==Register values:
rax = 0x0000100000000000  rbx = 0x00007ffeecc08600  rcx = 0x0000100021032a34  rdx = 0x0000100000000000  
rdi = 0x0000000000000000  rsi = 0x0000000000000000  rbp = 0x00007ffeecc08710  rsp = 0x00007ffeecc084e0  
 r8 = 0x0000100000000000   r9 = 0x0000100000000000  r10 = 0x0000100000000000  r11 = 0x0000000000000016  
r12 = 0x00001fffdd98109c  r13 = 0x00007ffeecc084e0  r14 = 0x00006170000f8a68  r15 = 0x00006170000f8880  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (QtQuick:x86_64+0x49e048) in QQuickWindowPrivate::renderSceneGraph(QSize const&, QSize const&)
==99820==ABORTING
 
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff733f52c6 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff734b0bf1 pthread_kill + 284
2   libsystem_c.dylib             	0x00007fff7335f6a6 abort + 127
3   libclang_rt.asan_osx_dynamic.dylib	0x0000000109e4c056 __sanitizer::Abort() + 70
4   libclang_rt.asan_osx_dynamic.dylib	0x0000000109e4a644 __sanitizer::Die() + 196
5   libclang_rt.asan_osx_dynamic.dylib	0x0000000109e2f296 __asan::ScopedInErrorReport::~ScopedInErrorReport() + 294
6   libclang_rt.asan_osx_dynamic.dylib	0x0000000109e2dba5 __asan::ReportDeadlySignal(__sanitizer::SignalContext const&) + 181
7   libclang_rt.asan_osx_dynamic.dylib	0x0000000109e2d424 __asan::AsanOnDeadlySignal(int, void*, void*) + 84
8   libsystem_platform.dylib      	0x00007fff734a5b5d _sigtramp + 29
9   ???                           	000000000000000000 0 + 0
10  org.qt-project.QtQuick        	0x00000001079911d5 QSGGuiThreadRenderLoop::renderWindow(QQuickWindow*) + 10533
11  org.qt-project.QtQuick        	0x0000000107b3ee25 QQuickWindow::event(QEvent*) + 1781
12  org.qt-project.QtWidgets      	0x0000000108aa964b QApplicationPrivate::notify_helper(QObject*, QEvent*) + 795
13  org.qt-project.QtWidgets      	0x0000000108aade8a QApplication::notify(QObject*, QEvent*) + 2234
14  org.qt-project.QtCore         	0x00000001043752cd QCoreApplication::notifyInternal2(QObject*, QEvent*) + 701
15  org.qt-project.QtGui          	0x0000000104e57b5a QPlatformWindow::deliverUpdateRequest() + 282
16  libqcocoa.dylib               	0x00000001102d003e QCocoaWindow::deliverUpdateRequest() + 606
17  libqcocoa.dylib               	0x0000000110296db2 QCocoaScreen::deliverUpdateRequests() + 1570
18  libclang_rt.asan_osx_dynamic.dylib	0x0000000109e285a6 __wrap_dispatch_source_set_event_handler_block_invoke + 214
19  libdispatch.dylib             	0x00007fff7326d63d _dispatch_client_callout + 8
20  libdispatch.dylib             	0x00007fff7326fde6 _dispatch_continuation_pop + 414
21  libdispatch.dylib             	0x00007fff7327ef42 _dispatch_source_invoke + 2056
22  libdispatch.dylib             	0x00007fff7327854b _dispatch_main_queue_callback_4CF + 813
23  com.apple.CoreFoundation      	0x00007fff47354a87 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
24  com.apple.CoreFoundation      	0x00007fff473541b1 __CFRunLoopRun + 2289
25  com.apple.CoreFoundation      	0x00007fff4735366e CFRunLoopRunSpecific + 455
26  com.apple.HIToolbox           	0x00007fff465b21ab RunCurrentEventLoopInMode + 292
27  com.apple.HIToolbox           	0x00007fff465b1ee5 ReceiveNextEventCommon + 603
28  com.apple.HIToolbox           	0x00007fff465b1c76 _BlockUntilNextEventMatchingListInModeWithFilter + 64
29  com.apple.AppKit              	0x00007fff4494a77d _DPSNextEvent + 1135
30  com.apple.AppKit              	0x00007fff4494946b -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361
31  com.apple.AppKit              	0x00007fff44943588 -[NSApplication run] + 699
32  libqcocoa.dylib               	0x0000000110316a05 QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 7061
33  org.qt-project.QtCore         	0x0000000104367297 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 1495
34  org.qt-project.QtCore         	0x00000001043771e3 QCoreApplication::exec() + 1091
35  org.example.tshnm-iso         	0x000000010300e0e2 TshnmApplication::doRun(int&, char**) + 242 (TshnmApplication.cpp:380)
36  libisle.dylib                 	0x00000001084fcf88 AbstractApplication::run(int&, char**) + 888 (AbstractApplication.cpp:48)
37  org.example.tshnm-iso         	0x0000000103037407 main + 71 (main.cpp:17)
38  org.example.tshnm-iso         	0x0000000102ff4754 start + 52

Thread 1:: QQmlThread
0   libsystem_kernel.dylib        	0x00007fff733f736e poll + 10
1   libclang_rt.asan_osx_dynamic.dylib	0x0000000109e0f347 wrap_poll + 1623
2   org.qt-project.QtCore         	0x00000001044b3d20 qt_safe_poll(pollfd*, unsigned int, timespec const*) + 800
3   org.qt-project.QtCore         	0x00000001044b96b3 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2739
4   org.qt-project.QtCore         	0x0000000104367297 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 1495
5   org.qt-project.QtCore         	0x0000000103d2e180 QThread::exec() + 528
6   org.qt-project.QtQml          	0x0000000106fc575a QQmlThreadPrivate::run() + 122
7   org.qt-project.QtCore         	0x0000000103d313f3 QThreadPrivate::start(void*) + 1123
8   libsystem_pthread.dylib       	0x00007fff734ae2eb _pthread_body + 126
9   libsystem_pthread.dylib       	0x00007fff734b1249 _pthread_start + 66
10  libsystem_pthread.dylib       	0x00007fff734ad40d thread_start + 13

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff733f2f32 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff7337e914 nanosleep + 199
2   libsystem_c.dylib             	0x00007fff7337e808 usleep + 53
3   libfmod.dylib                 	0x000000010ae426ad 0x10ae41000 + 5805
4   libfmod.dylib                 	0x000000010aebfffa 0x10ae41000 + 520186
5   libfmod.dylib                 	0x000000010ae42707 0x10ae41000 + 5895
6   libsystem_pthread.dylib       	0x00007fff734ae2eb _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff734b1249 _pthread_start + 66
8   libsystem_pthread.dylib       	0x00007fff734ad40d thread_start + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff733ef266 semaphore_wait_trap + 10
1   libfmod.dylib                 	0x000000010ae42b40 0x10ae41000 + 6976
2   libfmod.dylib                 	0x000000010aebffc3 0x10ae41000 + 520131
3   libfmod.dylib                 	0x000000010ae42707 0x10ae41000 + 5895
4   libsystem_pthread.dylib       	0x00007fff734ae2eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff734b1249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff734ad40d thread_start + 13

Thread 4:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib        	0x00007fff733ef22a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff733ef76c mach_msg + 60
2   com.apple.audio.CoreAudio     	0x00007fff46dc3eda HALB_MachPort::SendMessageWithReply(unsigned int, unsigned int, unsigned int, unsigned int, mach_msg_header_t*, bool, unsigned int) + 122
3   com.apple.audio.CoreAudio     	0x00007fff46dc3e4f HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 45
4   com.apple.audio.CoreAudio     	0x00007fff46dc039f HALC_ProxyIOContext::IOWorkLoop() + 1017
5   com.apple.audio.CoreAudio     	0x00007fff46dbfdf4 HALC_ProxyIOContext::IOThreadEntry(void*) + 122
6   com.apple.audio.CoreAudio     	0x00007fff46dbf956 HALB_IOThread::Entry(void*) + 72
7   libsystem_pthread.dylib       	0x00007fff734ae2eb _pthread_body + 126
8   libsystem_pthread.dylib       	0x00007fff734b1249 _pthread_start + 66
9   libsystem_pthread.dylib       	0x00007fff734ad40d thread_start + 13

Thread 5:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff733ef22a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff733ef76c mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff4735499e __CFRunLoopServiceMachPort + 328
3   com.apple.CoreFoundation      	0x00007fff47353f0c __CFRunLoopRun + 1612
4   com.apple.CoreFoundation      	0x00007fff4735366e CFRunLoopRunSpecific + 455
5   com.apple.AppKit              	0x00007fff449524a2 _NSEventThread + 175
6   libsystem_pthread.dylib       	0x00007fff734ae2eb _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff734b1249 _pthread_start + 66
8   libsystem_pthread.dylib       	0x00007fff734ad40d thread_start + 13

Thread 6:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	0x00007fff733f661a __select + 10
1   com.apple.CoreFoundation      	0x00007fff47382322 __CFSocketManager + 635
2   libsystem_pthread.dylib       	0x00007fff734ae2eb _pthread_body + 126
3   libsystem_pthread.dylib       	0x00007fff734b1249 _pthread_start + 66
4   libsystem_pthread.dylib       	0x00007fff734ad40d thread_start + 13

Thread 7:
0   libsystem_pthread.dylib       	0x00007fff734ad3f0 start_wqthread + 0

Thread 8:: CVDisplayLink
0   libsystem_kernel.dylib        	0x00007fff733f286a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff734b15a1 _pthread_cond_wait + 773
2   com.apple.CoreVideo           	0x00007fff490c2797 CVDisplayLink::waitUntil(unsigned long long) + 229
3   com.apple.CoreVideo           	0x00007fff490c1d46 CVDisplayLink::runIOThread() + 482
4   libsystem_pthread.dylib       	0x00007fff734ae2eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff734b1249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff734ad40d thread_start + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000108a4f5c0  rcx: 0x000000010b3b1e68  rdx: 0x0000000000000000
  rdi: 0x0000000000000307  rsi: 0x0000000000000006  rbp: 0x000000010b3b1ea0  rsp: 0x000000010b3b1e68
   r8: 0x000000010a494739   r9: 0x000000000000f1d7  r10: 0x0000000000000000  r11: 0x0000000000000206
  r12: 0x0000000000000307  r13: 0x00007ffeecc084e0  r14: 0x0000000000000006  r15: 0x000000000000002d
  rip: 0x00007fff733f52c6  rfl: 0x0000000000000206  cr2: 0x00007fffa9b4e1a8
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133
```

**Comment by nicolasfella** [comment]
I can reproduce this with Qt 5.14.0 on Linux

#0  0x00007fa970ceb098 in QQuickWindowPrivate::renderSceneGraph (this=this@entry=0x55f58a12ebb0, size=..., surfaceSize=...) at items/qquickwindow.cpp:551
#1  0x00007fa970c8067c in QSGRenderThread::syncAndRender (this=this@entry=0x7fa950003a00, grabImage=grabImage@entry=0x0)
    at /home/nico/workspace/qt5/qtbase/include/QtGui/5.14.0/QtGui/private/../../../../../src/gui/rhi/qrhi_p.h:1250
#2  0x00007fa970c84871 in QSGRenderThread::run (this=0x7fa950003a00) at scenegraph/qsgthreadedrenderloop.cpp:990
#3  0x00007fa9710e4624 in QThreadPrivate::start (arg=0x7fa950003a00) at thread/qthread_unix.cpp:342
#4  0x00007fa96fcc04cf in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007fa96f88d2d3 in clone () from /usr/lib/libc.so.6

**Comment by yuthikasagarage** [comment]
same happens to me
