### ISSUE TITLE
Gammaray does not launch on Wayland with 2x scaling

### ISSUE THREAD

**Issue by nicolasfella** [KDAB/GammaRay#607]
When running something like `gammaray qmlscene foo.qml` the app does not start and eventually times out.
```
Detected ABI qt5_15-x86_64, using ABI qt5_15-x86_64.
Target not responding - timeout. Try setting the env variable GAMMARAY_LAUNCHER_TIMEOUT to a bigger value (in seconds).
See <https://github.com/KDAB/GammaRay/wiki/Known-Issues> for troubleshooting
```

The actual application does not seem to matter.

What seems to matter is:
- Wayland. On an X11 session or forcing `QT_QPA_PLATFORM=xcb` it works fine
- 200% scaling. When not using scaling or 200% scaling on X11 it works fine

Qt is self-built from 5.15 branch.

I have a backtrace, but it's not really telling
```
Thread 2 (Thread 0x7f15f3013700 (LWP 12872)):
#0  0x00007f15f88b305f in poll () from /usr/lib/libc.so.6
#1  0x00007f15f6201168 in ?? () from /usr/lib/libglib-2.0.so.0
#2  0x00007f15f61b2221 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#3  0x00007f15f9000e6f in QEventDispatcherGlib::processEvents (this=0x7f15ec000b60, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#4  0x00007f15f8fa834b in QEventLoop::exec (this=this@entry=0x7f15f3012d90, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:141
#5  0x00007f15f8dca0fe in QThread::exec (this=<optimized out>) at ../../include/QtCore/../../src/corelib/global/qflags.h:121
#6  0x00007f15f56fea97 in QDBusConnectionManager::run (this=0x7f15f576cd80 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>) at qdbusconnection.cpp:179
#7  0x00007f15f8dcb241 in QThreadPrivate::start (arg=0x7f15f576cd80 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>) at thread/qthread_unix.cpp:329
#8  0x00007f15f85ca422 in start_thread () from /usr/lib/libpthread.so.0
#9  0x00007f15f88bdbf3 in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7f15f5bd27c0 (LWP 12871)):
#0  0x00007f15f88b305f in poll () from /usr/lib/libc.so.6
#1  0x00007f15f6201168 in ?? () from /usr/lib/libglib-2.0.so.0
#2  0x00007f15f61b2221 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#3  0x00007f15f9000e8b in QEventDispatcherGlib::processEvents (this=0x55a54845aba0, flags=...) at kernel/qeventdispatcher_glib.cpp:425
#4  0x00007f15f8fa834b in QEventLoop::exec (this=this@entry=0x7ffc3ede0e70, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:141
#5  0x00007f15f8fb05c0 in QCoreApplication::exec () at ../../include/QtCore/../../src/corelib/global/qflags.h:121
#6  0x000055a5479b5007 in main (argc=3, argv=0x7ffc3ede10c8) at /home/nico/workspace/GammaRay/launcher/cli/main.cpp:352
```

Some printf debugging makes me conclude that the lockup happens somewhere in https://github.com/KDAB/GammaRay/blob/master/core/probe.cpp#L542

**Comment by milianw** [comment]
Better backtrace, seems to occur when QThreadPool is initialized while the probe lock is held. affects hidpi screens e.g.:

```
(gdb) thread apply all bt

Thread 8 (Thread 0x7fffd3fff640 (LWP 181607)):
#0  0x00007ffff60f7d5d in syscall () from /usr/lib/libc.so.6
#1  0x00007ffff65b8166 in QBasicMutex::lockInternal() () from /usr/lib/libQt5Core.so.5
#2  0x00007ffff65b8474 in ?? () from /usr/lib/libQt5Core.so.5
#3  0x00007ffff7e818ce in QMutexLocker::QMutexLocker (this=0x7fffd3ffebe8, m=0x7ffff7f84838 <(anonymous namespace)::Q_QGS_s_lock::innerFunction()::holder>) at /usr/include/qt/QtCore/qmutex.h:233
#4  0x00007ffff7eaa85d in GammaRay::Probe::objectAdded (obj=0x7fffcc000b60, fromCtor=true) at ../core/probe.cpp:544
#5  0x000055555559bc2e in gammaray_addObject (obj=0x7fffcc000b60) at ../probe/hooks.cpp:94
#6  0x00007ffff67d202d in QObject::QObject(QObjectPrivate&, QObject*) () from /usr/lib/libQt5Core.so.5
#7  0x00007ffff67999fa in QAbstractEventDispatcher::QAbstractEventDispatcher(QAbstractEventDispatcherPrivate&, QObject*) () from /usr/lib/libQt5Core.so.5
#8  0x00007ffff67f5d22 in QEventDispatcherGlib::QEventDispatcherGlib(QObject*) () from /usr/lib/libQt5Core.so.5
#9  0x00007ffff65b7471 in ?? () from /usr/lib/libQt5Core.so.5
#10 0x00007ffff65b6140 in ?? () from /usr/lib/libQt5Core.so.5
#11 0x00007ffff65b7f39 in ?? () from /usr/lib/libQt5Core.so.5
#12 0x00007ffff5f0c3e9 in start_thread () from /usr/lib/libpthread.so.0
#13 0x00007ffff60fd293 in clone () from /usr/lib/libc.so.6

Thread 7 (Thread 0x7fffe8eb3640 (LWP 181606)):
#0  0x00007ffff60f7d5d in syscall () from /usr/lib/libc.so.6
#1  0x00007ffff65b8166 in QBasicMutex::lockInternal() () from /usr/lib/libQt5Core.so.5
#2  0x00007ffff65b8474 in ?? () from /usr/lib/libQt5Core.so.5
#3  0x00007ffff7e818ce in QMutexLocker::QMutexLocker (this=0x7fffe8eb2be8, m=0x7ffff7f84838 <(anonymous namespace)::Q_QGS_s_lock::innerFunction()::holder>) at /usr/include/qt/QtCore/qmutex.h:233
#4  0x00007ffff7eaa85d in GammaRay::Probe::objectAdded (obj=0x7fffd8000b60, fromCtor=true) at ../core/probe.cpp:544
#5  0x000055555559bc2e in gammaray_addObject (obj=0x7fffd8000b60) at ../probe/hooks.cpp:94
#6  0x00007ffff67d202d in QObject::QObject(QObjectPrivate&, QObject*) () from /usr/lib/libQt5Core.so.5
#7  0x00007ffff67999fa in QAbstractEventDispatcher::QAbstractEventDispatcher(QAbstractEventDispatcherPrivate&, QObject*) () from /usr/lib/libQt5Core.so.5
#8  0x00007ffff67f5d22 in QEventDispatcherGlib::QEventDispatcherGlib(QObject*) () from /usr/lib/libQt5Core.so.5
#9  0x00007ffff65b7471 in ?? () from /usr/lib/libQt5Core.so.5
#10 0x00007ffff65b6140 in ?? () from /usr/lib/libQt5Core.so.5
#11 0x00007ffff65b7f39 in ?? () from /usr/lib/libQt5Core.so.5
#12 0x00007ffff5f0c3e9 in start_thread () from /usr/lib/libpthread.so.0
#13 0x00007ffff60fd293 in clone () from /usr/lib/libc.so.6

Thread 6 (Thread 0x7fffe96b4640 (LWP 181605)):
#0  0x00007ffff60f7d5d in syscall () from /usr/lib/libc.so.6
#1  0x00007ffff65b8166 in QBasicMutex::lockInternal() () from /usr/lib/libQt5Core.so.5
#2  0x00007ffff65b8474 in ?? () from /usr/lib/libQt5Core.so.5
#3  0x00007ffff7e818ce in QMutexLocker::QMutexLocker (this=0x7fffe96b3be8, m=0x7ffff7f84838 <(anonymous namespace)::Q_QGS_s_lock::innerFunction()::holder>) at /usr/include/qt/QtCore/qmutex.h:233
#4  0x00007ffff7eaa85d in GammaRay::Probe::objectAdded (obj=0x7fffd4000b60, fromCtor=true) at ../core/probe.cpp:544
#5  0x000055555559bc2e in gammaray_addObject (obj=0x7fffd4000b60) at ../probe/hooks.cpp:94
#6  0x00007ffff67d202d in QObject::QObject(QObjectPrivate&, QObject*) () from /usr/lib/libQt5Core.so.5
--Type <RET> for more, q to quit, c to continue without paging--
#7  0x00007ffff67999fa in QAbstractEventDispatcher::QAbstractEventDispatcher(QAbstractEventDispatcherPrivate&, QObject*) () from /usr/lib/libQt5Core.so.5
#8  0x00007ffff67f5d22 in QEventDispatcherGlib::QEventDispatcherGlib(QObject*) () from /usr/lib/libQt5Core.so.5
#9  0x00007ffff65b7471 in ?? () from /usr/lib/libQt5Core.so.5
#10 0x00007ffff65b6140 in ?? () from /usr/lib/libQt5Core.so.5
#11 0x00007ffff65b7f39 in ?? () from /usr/lib/libQt5Core.so.5
#12 0x00007ffff5f0c3e9 in start_thread () from /usr/lib/libpthread.so.0
#13 0x00007ffff60fd293 in clone () from /usr/lib/libc.so.6

Thread 5 (Thread 0x7fffe9eb5640 (LWP 181604)):
#0  0x00007ffff60f7d5d in syscall () from /usr/lib/libc.so.6
#1  0x00007ffff65b8166 in QBasicMutex::lockInternal() () from /usr/lib/libQt5Core.so.5
#2  0x00007ffff65b8474 in ?? () from /usr/lib/libQt5Core.so.5
#3  0x00007ffff7e818ce in QMutexLocker::QMutexLocker (this=0x7fffe9eb4be8, m=0x7ffff7f84838 <(anonymous namespace)::Q_QGS_s_lock::innerFunction()::holder>) at /usr/include/qt/QtCore/qmutex.h:233
#4  0x00007ffff7eaa85d in GammaRay::Probe::objectAdded (obj=0x7fffe0000b60, fromCtor=true) at ../core/probe.cpp:544
#5  0x000055555559bc2e in gammaray_addObject (obj=0x7fffe0000b60) at ../probe/hooks.cpp:94
#6  0x00007ffff67d202d in QObject::QObject(QObjectPrivate&, QObject*) () from /usr/lib/libQt5Core.so.5
#7  0x00007ffff67999fa in QAbstractEventDispatcher::QAbstractEventDispatcher(QAbstractEventDispatcherPrivate&, QObject*) () from /usr/lib/libQt5Core.so.5
#8  0x00007ffff67f5d22 in QEventDispatcherGlib::QEventDispatcherGlib(QObject*) () from /usr/lib/libQt5Core.so.5
#9  0x00007ffff65b7471 in ?? () from /usr/lib/libQt5Core.so.5
#10 0x00007ffff65b6140 in ?? () from /usr/lib/libQt5Core.so.5
#11 0x00007ffff65b7f39 in ?? () from /usr/lib/libQt5Core.so.5
#12 0x00007ffff5f0c3e9 in start_thread () from /usr/lib/libpthread.so.0
#13 0x00007ffff60fd293 in clone () from /usr/lib/libc.so.6

Thread 4 (Thread 0x7fffeadee640 (LWP 181603)):
#0  0x00007ffff60f246f in poll () from /usr/lib/libc.so.6
#1  0x00007ffff51e8168 in ?? () from /usr/lib/libglib-2.0.so.0
#2  0x00007ffff5199221 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#3  0x00007ffff67f5311 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5                                                                                                                   
#4  0x00007ffff679b11c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#5  0x00007ffff65b6c32 in QThread::exec() () from /usr/lib/libQt5Core.so.5
#6  0x00007ffff65b7e0f in ?? () from /usr/lib/libQt5Core.so.5
#7  0x00007ffff5f0c3e9 in start_thread () from /usr/lib/libpthread.so.0
#8  0x00007ffff60fd293 in clone () from /usr/lib/libc.so.6

Thread 3 (Thread 0x7fffebfff640 (LWP 181602)):
#0  0x00007ffff60f246f in poll () from /usr/lib/libc.so.6
#1  0x00007ffff51e8168 in ?? () from /usr/lib/libglib-2.0.so.0
#2  0x00007ffff5199221 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#3  0x00007ffff67f5311 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5                                                                                                                   
#4  0x00007ffff679b11c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
--Type <RET> for more, q to quit, c to continue without paging--
#5  0x00007ffff65b6c32 in QThread::exec() () from /usr/lib/libQt5Core.so.5
#6  0x00007ffff274c098 in ?? () from /usr/lib/libQt5DBus.so.5
#7  0x00007ffff65b7e0f in ?? () from /usr/lib/libQt5Core.so.5
#8  0x00007ffff5f0c3e9 in start_thread () from /usr/lib/libpthread.so.0
#9  0x00007ffff60fd293 in clone () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7ffff2588640 (LWP 181601)):
#0  0x00007ffff60f246f in poll () from /usr/lib/libc.so.6
#1  0x00007ffff2f5d63b in ?? () from /usr/lib/libxcb.so.1
#2  0x00007ffff2f5f37b in xcb_wait_for_event () from /usr/lib/libxcb.so.1
#3  0x00007ffff2863c51 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#4  0x00007ffff65b7e0f in ?? () from /usr/lib/libQt5Core.so.5
#5  0x00007ffff5f0c3e9 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007ffff60fd293 in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7ffff2f3b800 (LWP 181597)):
#0  0x00007ffff60f7d5d in syscall () from /usr/lib/libc.so.6
#1  0x00007ffff65ba0c2 in QSemaphore::acquire(int) () from /usr/lib/libQt5Core.so.5
#2  0x00007ffff6bd7fba in ?? () from /usr/lib/libQt5Gui.so.5
#3  0x00007ffff6bc637c in QImage::convertToFormat_helper(QImage::Format, QFlags<Qt::ImageConversionFlag>) const () from /usr/lib/libQt5Gui.so.5                                                                                                         
#4  0x00007ffff6c01285 in QRasterPlatformPixmap::createPixmapForImage(QImage, QFlags<Qt::ImageConversionFlag>) () from /usr/lib/libQt5Gui.so.5                                                                                                          
#5  0x00007ffff6c015bd in QRasterPlatformPixmap::fromImage(QImage const&, QFlags<Qt::ImageConversionFlag>) () from /usr/lib/libQt5Gui.so.5                                                                                                              
#6  0x00007ffff6bf7d74 in QPixmap::fromImage(QImage const&, QFlags<Qt::ImageConversionFlag>) () from /usr/lib/libQt5Gui.so.5
#7  0x00007ffff6bf9142 in QPixmap::convertFromImage(QImage const&, QFlags<Qt::ImageConversionFlag>) () from /usr/lib/libQt5Gui.so.5                                                                                                                     
#8  0x00007ffff6c054b8 in QPixmapIconEngine::addFile(QString const&, QSize const&, QIcon::Mode, QIcon::State) () from /usr/lib/libQt5Gui.so.5                                                                                                           
#9  0x00007ffff6c07e21 in QIcon::addFile(QString const&, QSize const&, QIcon::Mode, QIcon::State) () from /usr/lib/libQt5Gui.so.5                                                                                                                       
#10 0x00007ffff053b410 in GammaRay::GuiSupport::createIcon (this=0x55555571a780, oldIcon=..., w=0x0) at ../plugins/guisupport/guisupport.cpp:1113
#11 0x00007ffff053bc92 in GammaRay::GuiSupport::updateWindowIcon (this=0x55555571a780, w=0x0) at ../plugins/guisupport/guisupport.cpp:1174
#12 0x00007ffff0529cdf in GammaRay::GuiSupport::GuiSupport (this=0x55555571a780, probe=0x55555574fbd0, parent=0x55555574fbd0) at ../plugins/guisupport/guisupport.cpp:141
#13 0x00007ffff058a41d in GammaRay::StandardToolFactory<QObject, GammaRay::GuiSupport>::init (this=0x55555571b960, probe=0x55555574fbd0) at ../core/toolfactory.h:139
#14 0x00007ffff7ed4466 in GammaRay::ProxyToolFactory::init (this=0x555555750250, probe=0x55555574fbd0) at ../core/proxytoolfactory.cpp:59
#15 0x00007ffff7ec9fe0 in GammaRay::ToolManager::objectAdded (this=0x55555571db10, mo=0x7ffff6a297e0 <QObject::staticMetaObject>) at ../core/toolmanager.cpp:214
#16 0x00007ffff7ec9e61 in GammaRay::ToolManager::objectAdded (this=0x55555571db10, mo=0x7ffff6a2d640 <QThread::staticMetaObj--Type <RET> for more, q to quit, c to continue without paging--
ect>) at ../core/toolmanager.cpp:206
#17 0x00007ffff7ec9d8c in GammaRay::ToolManager::objectAdded (this=0x55555571db10, obj=0x5555555dd9f0) at ../core/toolmanager.cpp:194
#18 0x00007ffff7eaaf55 in GammaRay::Probe::objectFullyConstructed (this=0x55555574fbd0, obj=0x5555555dd9f0) at ../core/probe.cpp:688
#19 0x00007ffff7eaaafd in GammaRay::Probe::objectAdded (obj=0x5555555dd9f0, fromCtor=false) at ../core/probe.cpp:612
#20 0x00007ffff7ea94b5 in GammaRay::Probe::createProbe (findExisting=true) at ../core/probe.cpp:345
#21 0x000055555559b5ac in GammaRay::ProbeCreator::createProbe (this=0x5555556dac20) at ../probe/probecreator.cpp:92
#22 0x000055555559ae36 in GammaRay::ProbeCreator::qt_static_metacall (_o=0x5555556dac20, _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x5555556d8018) at probe/gammaray_probe_obj_autogen/EWIEGA46WW/moc_probecreator.cpp:72
#23 0x00007ffff67c91b2 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#24 0x00007ffff679c79a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#25 0x00007ffff679f283 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
#26 0x00007ffff67f5cd4 in ?? () from /usr/lib/libQt5Core.so.5
#27 0x00007ffff519a43c in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#28 0x00007ffff51e81d9 in ?? () from /usr/lib/libglib-2.0.so.0
#29 0x00007ffff5199221 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#30 0x00007ffff67f5382 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#31 0x00007ffff679c8d2 in QCoreApplication::processEvents(QFlags<QEventLoop::ProcessEventsFlag>, int) () from /usr/lib/libQt5Core.so.5
#32 0x00007ffff67f0f01 in QTest::qWait(int) () from /usr/lib/libQt5Core.so.5
#33 0x00005555555a1b31 in QuickInspectorPickingTest::createProbe (this=0x7fffffffc1b0) at ../tests/quickinspectorpickingtest.cpp:63
#34 0x00005555555a1f9a in QuickInspectorPickingTest::init (this=0x7fffffffc1b0) at ../tests/quickinspectorpickingtest.cpp:105
#35 0x00005555555a079d in QuickInspectorPickingTest::qt_static_metacall (_o=0x7fffffffc1b0, _c=QMetaObject::InvokeMetaMethod, _id=1, _a=0x7fffffffb980) at tests/quickinspectorpickingtest_autogen/include/quickinspectorpickingtest.moc:86
#36 0x00007ffff67aae16 in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const () from /usr/lib/libQt5Core.so.5
#37 0x00007ffff7d3fe2d in ?? () from /usr/lib/libQt5Test.so.5
#38 0x00007ffff7d405b1 in ?? () from /usr/lib/libQt5Test.so.5
#39 0x00007ffff7d40b64 in ?? () from /usr/lib/libQt5Test.so.5
#40 0x00007ffff7d4102e in QTest::qRun() () from /usr/lib/libQt5Test.so.5
#41 0x00007ffff7d413de in QTest::qExec(QObject*, int, char**) () from /usr/lib/libQt5Test.so.5
#42 0x00005555555a06d2 in main (argc=1, argv=0x7fffffffc2f8) at ../tests/quickinspectorpickingtest.cpp:174
(gdb)
```
