### ISSUE TITLE
Crash while inspecting context properties

### ISSUE THREAD

**Issue by ratijas** [KDAB/GammaRay#680]
While inspecting stack of QML contexts on a plasmoid's object, the process to which GammaRay was attached crashed somewhere inside injected GammaRay's code:

```
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `plasmashell'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f60e1301d22 in raise () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f60dd205ac0 (LWP 205819))]
(gdb) bt
#0  0x00007f60e1301d22 in raise () at /usr/lib/libc.so.6
#1  0x00007f60e4092987 in KCrash::defaultCrashHandler(int) (sig=11) at /home/ratijas/kde/src/frameworks/kcrash/src/kcrash.cpp:609
#2  0x00007f60e1301da0 in <signal handler called> () at /usr/lib/libc.so.6
#3  0x00007f60e1e672a4 in QWindow::transientParent() const () at /usr/lib/libQt5Gui.so.5
#4  0x00007f60ce2f0108 in QMenuProxy::transientParent() (this=0x55aba12f3520) at /home/ratijas/kde/src/frameworks/plasma-framework/src/declarativeimports/plasmacomponents/qmenu.cpp:112
#5  0x00007f60ce2e5396 in QMenuProxy::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x55aba12f3520, _c=QMetaObject::ReadProperty, _id=1, _a=0x7ffe80e248a0)
    at /home/ratijas/kde/build/frameworks/plasma-framework/src/declarativeimports/plasmacomponents/plasmacomponentsplugin_autogen/EWIEGA46WW/moc_qmenu.cpp:321
#6  0x00007f60ce2e5682 in QMenuProxy::qt_metacall(QMetaObject::Call, int, void**) (this=0x55aba12f3520, _c=QMetaObject::ReadProperty, _id=1, _a=0x7ffe80e248a0)
    at /home/ratijas/kde/build/frameworks/plasma-framework/src/declarativeimports/plasmacomponents/plasmacomponentsplugin_autogen/EWIEGA46WW/moc_qmenu.cpp:398
#7  0x00007f60e1aa3cdd in QMetaProperty::read(QObject const*) const () at /usr/lib/libQt5Core.so.5
#8  0x00007f60b201cde8 in GammaRay::QMetaPropertyAdaptor::propertyData(int) const () at /home/ratijas/kde/usr/lib/gammaray/3.0/qt5_15-x86_64/../../../libgammaray_core-qt5_15-x86_64.so.3.0.0
#9  0x00007f60b201a586 in GammaRay::PropertyAggregator::propertyData(int) const () at /home/ratijas/kde/usr/lib/gammaray/3.0/qt5_15-x86_64/../../../libgammaray_core-qt5_15-x86_64.so.3.0.0
#10 0x00007f60b1fcead5 in GammaRay::AggregatedPropertyModel::itemData(QModelIndex const&) const () at /home/ratijas/kde/usr/lib/gammaray/3.0/qt5_15-x86_64/../../../libgammaray_core-qt5_15-x86_64.so.3.0.0
#11 0x00007f60b204ff43 in GammaRay::RemoteModelServer::newRequest(GammaRay::Message const&) () at /home/ratijas/kde/usr/lib/gammaray/3.0/qt5_15-x86_64/../../../libgammaray_core-qt5_15-x86_64.so.3.0.0
#12 0x00007f60e1aa26ab in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const () at /usr/lib/libQt5Core.so.5
#13 0x00007f60b1f42922 in GammaRay::Endpoint::dispatchMessage(GammaRay::Message const&) () at /home/ratijas/kde/usr/lib/gammaray/3.0/qt5_15-x86_64/../../../libgammaray_common-qt5_15-x86_64.so.3.0.0
#14 0x00007f60b1f3f080 in GammaRay::Endpoint::readyRead() () at /home/ratijas/kde/usr/lib/gammaray/3.0/qt5_15-x86_64/../../../libgammaray_common-qt5_15-x86_64.so.3.0.0
#15 0x00007f60e1ac473c in  () at /usr/lib/libQt5Core.so.5
#16 0x00007f60e2459130 in  () at /usr/lib/libQt5Network.so.5
#17 0x00007f60e246fa0a in  () at /usr/lib/libQt5Network.so.5
#18 0x00007f60e29281a6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#19 0x00007f60e1a9416a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#20 0x00007f60e1ade276 in  () at /usr/lib/libQt5Core.so.5
#21 0x00007f60dfd37f13 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#22 0x00007f60dfd8e0d9 in  () at /usr/lib/libglib-2.0.so.0
#23 0x00007f60dfd35485 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#24 0x00007f60e1adf4c7 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#25 0x00007f60e1a8c44b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#26 0x00007f60e1a97b97 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#27 0x000055ab9db2b7cc in main(int, char**) (argc=1, argv=0x7ffe80e25bb8) at /home/ratijas/kde/src/kde/workspace/plasma-workspace/shell/main.cpp:238
```

**Comment by ratijas** [comment]
This is a very consistent crash.

Steps to reproduce (probably could be reduced):

https://user-images.githubusercontent.com/6737986/152468561-97cd1bdf-0f0e-4c5d-b56c-50981092f93e.mp4

**Comment by Waqar144** [comment]
This is crashing inside plasmashell, not gammaray:

```
#4  0x00007f60ce2f0108 in QMenuProxy::transientParent() (this=0x55aba12f3520) at /home/ratijas/kde/src/frameworks/plasma-framework/src/declarativeimports/plasmacomponents/qmenu.cpp:112

```

Gammaray sometimes accesses things in an unnatural way for which apps are often not prepared so they can crash.
