### ISSUE TITLE
Crash while inspecting plasma-systemmonitor

### ISSUE THREAD

**Issue by ratijas** [KDAB/GammaRay#870]
Crashed while looking at plasma-systemmonitor through GammaRay, switching pages etc.

<details>

<summary>Traceback</summary>

```gdb
Application: System Monitor (plasma-systemmonitor), signal: Aborted
Content of s_kcrashErrorMessage: std::unique_ptr<char []> = {get() = 0x0}
[KCrash Handler]
#5  0x00007f95f50ac83c in  () at /usr/lib/libc.so.6
#6  0x00007f95f505c668 in raise () at /usr/lib/libc.so.6
#7  0x00007f95f50444b8 in abort () at /usr/lib/libc.so.6
#8  0x00007f95f529ca6f in __gnu_cxx::__verbose_terminate_handler() () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#9  0x00007f95f52b011c in __cxxabiv1::__terminate(void (*)()) (handler=<optimized out>) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#10 0x00007f95f52b0189 in std::terminate() () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#11 0x00007f95f52b03ed in __cxxabiv1::__cxa_throw(void*, std::type_info*, void (*)(void*)) (obj=<optimized out>, tinfo=0x7f95f546c0e8 <typeinfo for std::out_of_range>, dest=0x7f95f52c85c0 <std::out_of_range::~out_of_range()>) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_throw.cc:98
#12 0x00007f95f52a021d in std::__throw_out_of_range(char const*) (__s=__s@entry=0x7f95f4fc1cbd "unordered_map::at") at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/functexcept.cc:86
#13 0x00007f95f4eeb203 in std::__detail::_Map_base<GammaRay::PropertyAdaptor*, std::pair<GammaRay::PropertyAdaptor* const, QList<GammaRay::PropertyAdaptor*> >, std::allocator<std::pair<GammaRay::PropertyAdaptor* const, QList<GammaRay::PropertyAdaptor*> > >, std::__detail::_Select1st, std::equal_to<GammaRay::PropertyAdaptor*>, std::hash<GammaRay::PropertyAdaptor*>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, true>::at(GammaRay::PropertyAdaptor* const&) (__k=<optimized out>, this=<optimized out>) at /usr/include/c++/13.2.1/bits/hashtable_policy.h:785
#14 std::unordered_map<GammaRay::PropertyAdaptor*, QList<GammaRay::PropertyAdaptor*>, std::hash<GammaRay::PropertyAdaptor*>, std::equal_to<GammaRay::PropertyAdaptor*>, std::allocator<std::pair<GammaRay::PropertyAdaptor* const, QList<GammaRay::PropertyAdaptor*> > > >::at(GammaRay::PropertyAdaptor* const&) (__k=<optimized out>, this=<optimized out>) at /usr/include/c++/13.2.1/bits/unordered_map.h:1004
#15 GammaRay::AggregatedPropertyModel::reloadSubTree(GammaRay::PropertyAdaptor*, int) (this=this@entry=0x55947b016590, parentAdaptor=<optimized out>, parentAdaptor@entry=0x559483deb580, index=index@entry=95) at /home/ratijas/kde/src6/gammaray/core/aggregatedpropertymodel.cpp:470
#16 0x00007f95f4eeb330 in GammaRay::AggregatedPropertyModel::propertyChanged(int, int) (this=0x55947b016590, first=<optimized out>, last=95) at /home/ratijas/kde/src6/gammaray/core/aggregatedpropertymodel.cpp:379
#17 0x00007f95f57b9403 in  () at /usr/lib/libQt6Core.so.6
#18 0x00007f95f4ec8ed8 in GammaRay::PropertyAdaptor::propertyChanged(int, int) (this=<optimized out>, _t1=<optimized out>, _t2=<optimized out>) at /home/ratijas/kde/build6/gammaray/core/gammaray_core_autogen/EWIEGA46WW/moc_propertyadaptor.cpp:236
#19 0x00007f95f57b9403 in  () at /usr/lib/libQt6Core.so.6
#20 0x00007f95f4ec8ed8 in GammaRay::PropertyAdaptor::propertyChanged(int, int) (this=<optimized out>, _t1=<optimized out>, _t2=<optimized out>) at /home/ratijas/kde/build6/gammaray/core/gammaray_core_autogen/EWIEGA46WW/moc_propertyadaptor.cpp:236
#21 0x00007f95f57b9526 in  () at /usr/lib/libQt6Core.so.6
#22 0x00007f95f6fd5c6b in QQuickItem::event(QEvent*) () at /usr/lib/libQt6Quick.so.6
#23 0x00007f95f777318b in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#24 0x00007f95f57626d8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#25 0x00007f95f7134923 in QQuickDeliveryAgentPrivate::clearFocusInScope(QQuickItem*, QQuickItem*, Qt::FocusReason, QFlags<QQuickDeliveryAgentPrivate::FocusOption>) () at /usr/lib/libQt6Quick.so.6
#26 0x00007f95f6fd3495 in QQuickItem::setFocus(bool, Qt::FocusReason) () at /usr/lib/libQt6Quick.so.6
#27 0x00007f95f600909c in QWindow::event(QEvent*) () at /usr/lib/libQt6Gui.so.6
#28 0x00007f95f777318b in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#29 0x00007f95f57626d8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#30 0x00007f95f5fa73b4 in QGuiApplicationPrivate::processActivatedEvent(QWindowSystemInterfacePrivate::ActivatedWindowEvent*) () at /usr/lib/libQt6Gui.so.6
#31 0x00007f95f60105dc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Gui.so.6
#32 0x00007f95f07b198f in  () at /usr/lib/qt6/plugins/platforms/../../../libQt6XcbQpa.so.6
#33 0x00007f95f42bef69 in  () at /usr/lib/libglib-2.0.so.0
#34 0x00007f95f431d327 in  () at /usr/lib/libglib-2.0.so.0
#35 0x00007f95f42bd162 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#36 0x00007f95f5997934 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#37 0x00007f95f576cc5e in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#38 0x00007f95f5765178 in QCoreApplication::exec() () at /usr/lib/libQt6Core.so.6
#39 0x0000559478dc4d0a in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /home/ratijas/kde/src6/plasma-systemmonitor/src/main.cpp:113
[Inferior 1 (process 29762) detached]
```

</details>

Operating System: Arch Linux 
KDE Plasma Version: 5.81.0 (git master)
KDE Frameworks Version: 5.245.0 (git master)
Qt Version: 6.6.0
Kernel Version: 6.6.1-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-6700HQ CPU @ 2.60GHz
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 970M/PCIe/SSE2

GammaRay: git master 8921c0a9bb31b26b3d5a1a32bdae136765d182a5

**Comment by Waqar144** [comment]
I am unable to even start the plasma-systemmonitor, perhaps you can provide more detailed instructions on how to build/run the software in question?

**Comment by Waqar144** [comment]
nevermind, reproduced with the system installed plasma-systemmonitor

**Comment by ratijas** [comment]
> I am unable to even start the plasma-systemmonitor, perhaps you can provide more detailed instructions on how to build/run the software in question?

What kind of issues were you facing? Mine builds fine with a regular kdesrc-build against Qt 6.6.0

**Comment by Waqar144** [comment]
I get: `plasma-systemmonitor: error while loading shared libraries: cannot apply additional memory protection after relocation: Cannot allocate memory`

Perhaps its because I am using an asan build

**Comment by ratijas** [comment]
> I get: plasma-systemmonitor: error while loading shared libraries: cannot apply additional memory protection after relocation: Cannot allocate memory

I've never seen such an error, wow

Thanks for the fix!
